version: '3.5'
services:
  postgres:
    build: ./docker/postgres/
    container_name: postgres-local
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password1
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: [ CMD-SHELL, pg_isready -U postgres ]
      interval: 5s
      timeout: 10s
      retries: 5
    command:
      postgres
      -c 'integrationtest.safe=1'

volumes:
  postgres:
