version: '3.5'
services:
    invoice-postgres:
        image: invoice-postgres:latest
        container_name: postgres-local-invoice
        # Connection defaults are defined in init-db.sql
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=password1
        ports:
            - "5432:5432"
        volumes:
            - invoice-testnet:/var/lib/postgresql/data

    redis:
        image: redis:5.0.7
        container_name: redis
        ports:
            - 6379:6379

volumes:
    invoice-testnet:
